default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: railsuser
  password: Kmzway87aa
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: rails_rest_api_development

test:
  <<: *default
  database: rails_rest_api_test

production:
  <<: *default
  database: rails_rest_api_production
  username: rails_rest_api
  password: <%= ENV['NAMADATABASE_DATABASE_PASSWORD'] %>
